quarkus.datasource.db-kind=postgresql

quarkus.ssm.endpoint-override=http://localhost:4566
quarkus.ssm.aws.region=us-east-1
quarkus.ssm.aws.credentials.type=static
quarkus.ssm.aws.credentials.static-provider.access-key-id=test
quarkus.ssm.aws.credentials.static-provider.secret-access-key=test
quarkus.ssm.config.enabled=false
quarkus.meeting-room.ssm.config.enabled=true
quarkus.meeting-room.ssm.config.path=meeting-room/dev/
quarkus.meeting-room.ssm.config.recursive=true
quarkus.meeting-room.ssm.config.with-decryption=true
# Instrumenta queries SQL no trace do OpenTelemetry — aparece como spans no Jaeger
quarkus.datasource.jdbc.telemetry=true

# ---------------------------------------------------------------
# JWT - Segurança
# ---------------------------------------------------------------
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=meeting-room-api
smallrye.jwt.sign.key.location=privateKey.pem
